- hosts: "{{myhosts}}"
  remote_user: ansible
  become: no
  connection: ssh
  gather_facts: "{{gather}}"
  vars:
    myhosts: ibmi
    gather: no
    pkg: yum

  tasks:
    - name: echo hello world
      command: echo hello world!

    - name: list yum packages
      command: /QOpenSys/pkgs/bin/yum list
      register: result

    - name: display result
      debug:
        var: result.stdout_lines

    - name: create a result file with all yum installed packages
      shell: echo "{{ result.stdout_lines | to_nice_yaml }}" > /tmp/result.txt

    - name: Store result file into /tmp/PUB400.COM/tmp/
      fetch:
        src: /tmp/result.txt
        dest: /tmp/

    - name: printing the library list
      shell: system "dsplibl *print" > /tmp/result.txt

    - name: formating the result
      shell: tail -n +4 /tmp/result.txt | sed '$d' | sed '$d' > /tmp/result2.txt
      register: result

    - name: retrieving the result file into linux ansible server
      fetch:
        src: /tmp/result2.txt
        dest: /tmp/

    # - name: display file
    #   shell: cat /tmp/result2.txt
    #   register: result

    # - name: display result
    #   debug:
    #     var: result.stdout_lines
